name: Check OpenAPI Schema

inputs:
  service-name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Checkout head branch
      uses: actions/checkout@v4
      with:
        path: head

    - name: Checkout base branch
      uses: actions/checkout@v4
      with:
        path: main

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Check for uncommitted changes
      shell: bash
      run: |
          echo "Backing up the existing OpenAPI schema..."
          cd head/${{ inputs.service-name }}
          mv openapi-schema.json current-openapi-schema.json

    - name: Build and generate OpenAPI schema
      shell: bash
      run: |
        cd head/${{ inputs.service-name }}
        dotnet build 
        echo "Checking for uncommitted changes in the OpenAPI schema..."
        if diff openapi-schema.json current-openapi-schema.json; then
            echo "No uncommitted changes detected in the OpenAPI schema."
        else
            echo "Uncommitted changes detected in the OpenAPI schema! Please update the OpenAPI schema by running the command 'dotnet build' in the ${ inputs.service-name } directory, and commit the changes."
            exit 1
        fi

    - name: Compare schemas
      shell: bash
      run: |
        echo "Comparing OpenAPI schemas..."
        docker run --rm \
        -v ${{ github.workspace }}/main/${{ inputs.service-name }}:/main \
        -v ${{ github.workspace }}/head/${{ inputs.service-name }}:/head \
        openapitools/openapi-diff:latest \
        --fail-on-incompatible \
        /main/openapi-schema.json \
        /head/openapi-schema.json