name: Check OpenAPI Schema

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
        
jobs:
  check-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head branch
        uses: actions/checkout@v4
        with:
          path: head

      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          path: main
          
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          
      - name: Download openapi-diff
        run: |
          curl -L -o openapi-diff.jar https://github.com/OpenAPITools/openapi-diff/releases/latest/download/openapi-diff.jar

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      
      - name: Build and generate OpenAPI schema
        run: | 
          dotnet build
          cp head/${{ inputs.service-name }}/bin/Debug/net9.0/openapi-schema.json head/${{ inputs.service-name }}/openapi-schema.json

      - name: Compare schemas
        run: |
          java -jar openapi-diff.jar \
            --fail-on-incompatible \
            main/${{ inputs.service-name }}/openapi-schema.json \
            head/${{ inputs.service-name }}/openapi-schema.json