name: Check OpenAPI Schema

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
        
jobs:
  check-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head branch
        uses: actions/checkout@v4
        with:
          path: head
      
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          path: main

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Compare schemas
        uses: mvegter/openapi-diff-action@v0.23.5
        with:
          head-spec: head/${{ inputs.service-name }}/spec/openapi-schema.json
          base-spec: main/${{ inputs.service-name }}/spec/openapi-schema.json