name: Group Microservice CI

on:
  pull_request:
    paths:
      - 'GroupMicroservice/**'
      - 'GroupMicroservice.Tests/**'
  workflow_call:

jobs:
  check-user-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check Group Microservice Schema diff
        uses: ./.github/actions/check-schema
        with:
          service-name: GroupMicroservice
  
  check-consumer-contract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check Group Microservice Consumer contract
        uses: ./.github/actions/check-consumer-contract
        with:
          base-dir: GroupMicroservice.Tests
          contract-file: GroupMicroservice-UserMicroservice.json