name: Group Microservice CI

on:
  pull_request:
    paths:
      - 'GroupMicroservice/**'
      - 'GroupMicroservice.Tests/**'
  workflow_call:
    secrets:
      PACT_BROKER:
        required: true
      PACT_BROKER_USERNAME:
        required: true
      PACT_BROKER_PASSWORD:
        required: true

jobs:
  check-openapi-schema:
    runs-on: ubuntu-latest
    name: Check OpenAPI Schema
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check Group Microservice Schema diff
        uses: ./.github/actions/check-schema
        with:
          service-name: GroupMicroservice
  
  consumer-contract-action:
    runs-on: ubuntu-latest
    name: Generate consumer contract
    needs: check-openapi-schema
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check Group Microservice Consumer contract
        uses: ./.github/actions/check-consumer-contract
        with:
          base-dir: GroupMicroservice.Tests
          contract-file: GroupMicroservice-UserMicroservice.json

      - name: Install Pact Broker CLI
        run: |
          echo "Installing Pact Broker CLI..."
          curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-ruby-standalone/master/install.sh | PACT_CLI_VERSION=v2.4.24 bash
        
      - name: Publish consumer contract
        run: |
          echo "Publishing consumer contract..."
          cd GroupMicroservice.Tests/pacts
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            pact-broker publish GroupMicroservice-UserMicroservice.json \
              --broker-base-url=${{ secrets.PACT_BROKER }} \
              --broker-username=${{ secrets.PACT_BROKER_USERNAME }} \
              --broker-password=${{ secrets.PACT_BROKER_PASSWORD }} \
              --consumer-app-version=${{ github.sha }} \
              --tag-with-git-branch \
              --tag=latest
          else
            pact-broker publish GroupMicroservice-UserMicroservice.json \
              --broker-base-url=${{ secrets.PACT_BROKER }} \
              --broker-username=${{ secrets.PACT_BROKER_USERNAME }} \
              --broker-password=${{ secrets.PACT_BROKER_PASSWORD }} \
              --consumer-app-version=${{ github.sha }} \
              --tag-with-git-branch
          fi