name: Group Microservice CI

on:
  pull_request:
    paths:
      - 'GroupMicroservice/**'
      - 'GroupMicroservice.Tests/**'
  workflow_call:

jobs:
  check-user-schema:
    name: Check Group Microservice Schema diff
    uses: ./.github/workflows/check-schema.yaml
    with:
      service-name: GroupMicroservice
  
  check-consumer-contract:
    name: Check Group Microservice Consumer contract
    uses: ./.github/workflows/check-consumer-contract.yaml
    with:
      base-dir: GroupMicroservice.Tests
      contract-file: pact/GroupMicroservice-UserMicroservice.json