name: Group Microservice CI

on:
  pull_request:
    paths:
      - 'GroupMicroservice/**'
      - 'GroupMicroservice.Tests/**'
  workflow_call:

jobs:
  check-user-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check Group Microservice Schema diff
        uses: ./.github/actions/check-schema
        with:
          service-name: GroupMicroservice
  
  consumer-contract-action:
    runs-on: ubuntu-latest
    env:
      BASE_DIR: GroupMicroservice.Tests
      CONTRACT_FILE: GroupMicroservice-UserMicroservice.json
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check Group Microservice Consumer contract
        uses: ./.github/actions/check-consumer-contract
        with:
          base-dir: ${{ env.BASE_DIR }}
          contract-file: ${{ env.CONTRACT_FILE }}

      - name: Install Pact Broker CLI
        run: |
          echo "Installing Pact Broker CLI..."
          curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-ruby-standalone/master/install.sh | PACT_CLI_VERSION=v2.4.24 bash

      - name: Publish consumer contract
        run: |
          echo "Publishing consumer contract..."
          cd ${{ env.BASE_DIR }}/pacts
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            pact-broker publish ${{ env.CONTRACT_FILE }} \
              --broker-base-url=${{ secrets.PACT_BROKER }} \
              --broker-username=${{ secrets.PACT_BROKER_USERNAME }} \
              --broker-password=${{ secrets.PACT_BROKER_PASSWORD }} \
              --consumer-app-version=${{ github.sha }} \
              --tag-with-git-branch \
              --tag=latest
          else
            pact-broker publish ${{ env.CONTRACT_FILE }} \
              --broker-base-url=${{ secrets.PACT_BROKER }} \
              --broker-username=${{ secrets.PACT_BROKER_USERNAME }} \
              --broker-password=${{ secrets.PACT_BROKER_PASSWORD }} \
              --consumer-app-version=${{ github.sha }} \
              --tag-with-git-branch
          fi