name: Group Microservice CI

on:
  pull_request:
    paths:
      - 'GroupMicroservice/**'
      - 'GroupMicroservice.Tests/**'
  workflow_call:

jobs:
  check-user-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check Group Microservice Schema diff
        uses: ./.github/actions/check-schema
        with:
          service-name: GroupMicroservice
  
  consumer-contract-action:
    runs-on: ubuntu-latest
    needs: check-user-schema
    env:
      BASE_DIR: GroupMicroservice.Tests
      CONTRACT_FILE: GroupMicroservice-UserMicroservice.json
      PACT_BROKER: ${{ secrets.PACT_BROKER }}
      PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
      PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check Group Microservice Consumer contract
        uses: ./.github/actions/check-consumer-contract
        with:
          base-dir: ${{ env.BASE_DIR }}
          contract-file: ${{ env.CONTRACT_FILE }}

      - name: Install Pact Broker CLI
        run: |
          echo "Installing Pact Broker CLI..."
          curl -fsSL https://raw.githubusercontent.com/pact-foundation/pact-ruby-standalone/master/install.sh | PACT_CLI_VERSION=v2.4.24 bash

      - name: Debug secrets
        run: |
          if [ -z "$PACT_BROKER" ]; then
            echo "PACT_BROKER is empty"
          else
            echo "PACT_BROKER is set"
          fi

          if [ -z "$PACT_BROKER_USERNAME" ]; then
            echo "PACT_BROKER_USERNAME is empty"
          else
            echo "PACT_BROKER_USERNAME is set"
          fi

          if [ -z "$PACT_BROKER_PASSWORD" ]; then
            echo "PACT_BROKER_PASSWORD is empty"
          else
            echo "PACT_BROKER_PASSWORD is set"
          fi
          
      - name: Publish consumer contract
        run: |
          echo "Publishing consumer contract..."
          cd ${{ env.BASE_DIR }}/pacts
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            pact-broker publish ${{ env.CONTRACT_FILE }} \
              --broker-base-url=$PACT_BROKER \
              --broker-username=$PACT_BROKER_USERNAME \
              --broker-password=$PACT_BROKER_PASSWORD \
              --consumer-app-version=${{ github.sha }} \
              --tag-with-git-branch \
              --tag=latest
          else
            pact-broker publish ${{ env.CONTRACT_FILE }} \
              --broker-base-url=$PACT_BROKER \
              --broker-username=$PACT_BROKER_USERNAME \
              --broker-password=$PACT_BROKER_PASSWORD \
              --consumer-app-version=${{ github.sha }} \
              --tag-with-git-branch
          fi