name: Group Microservice CI

on:
  pull_request:
    paths:
      - 'GroupMicroservice/**'
      - 'GroupMicroservice.Tests/**'
      - '.github/workflows/**'
      - '.github/actions/**'
  workflow_call:
    secrets:
      PACT_BROKER:
        required: true
      PACT_BROKER_USERNAME:
        required: true
      PACT_BROKER_PASSWORD:
        required: true
  workflow_dispatch: 
    

jobs:
  check-openapi-schema:
    runs-on: ubuntu-latest
    name: Check OpenAPI Schema
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Check Group Microservice Schema diff
        uses: ./.github/actions/check-schema
        with:
          service-name: GroupMicroservice
  
  consumer-contract-action:
    runs-on: ubuntu-latest
    name: Generate consumer contract
    needs: check-openapi-schema
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check Group Microservice Consumer contract
        uses: ./.github/actions/check-consumer-contract
        with:
          base-dir: GroupMicroservice.Tests
          contract-file: GroupMicroservice-UserMicroservice.json
          pact-broker: ${{ secrets.PACT_BROKER }} 
          pact-broker-username: ${{ secrets.PACT_BROKER_USERNAME }}
          pact-broker-password: ${{ secrets.PACT_BROKER_PASSWORD }}