name: User Microservice CI

on:
  pull_request:
    paths:
      - 'UserMicroservice/**'
      - 'UserMicroservice.Tests/**'
      - '.github/workflows/user-ms-workflow.yaml'
      - '.github/actions/check-schema/**'
      - '.github/actions/verify-pact-contract/**'
  workflow_call:
    secrets:
      PACT_BROKER:
        required: true
      PACT_BROKER_USERNAME:
        required: true
      PACT_BROKER_PASSWORD:
        required: true
  workflow_dispatch:
    inputs:
      group-ms-branch:
        description: 'Branch name in Group Microservice'
        required: true
        default: 'main'

jobs:
  check-openapi-schema:
    runs-on: ubuntu-latest
    name: Check OpenAPI Schema
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check User Microservice Schema diff
        uses: ./.github/actions/check-schema
        with:
          service-name: UserMicroservice
  
  verify-contract:
    runs-on: ubuntu-latest
    name: Verify consumer contract
    needs: check-openapi-schema
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Extract Group MS branch from PR description
        if: ${{ github.event_name == 'pull_request' }}
        id: extract-branch
        run: |
          echo "PR_BODY=${{ github.event.pull_request.body }}" >> $GITHUB_ENV
          GROUP_MS_BRANCH=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=GroupMS: )[^\s]+')
          echo "group-ms-branch=${GROUP_MS_BRANCH:-main}" >> $GITHUB_ENV
          echo "The branch name in Group Microservice is: $GROUP_MS_BRANCH"
      
      - name: Verify consumer contract
        uses: ./.github/actions/verify-pact-contract
        with:
          pact_broker: ${{ secrets.PACT_BROKER }}
          pact_broker_username: ${{ secrets.PACT_BROKER_USERNAME }}
          pact_broker_password: ${{ secrets.PACT_BROKER_PASSWORD }}
          consumer_tags: ${{ env.group-ms-branch || inputs.group-ms-branch }}
