name: User Microservice CI

on:
  pull_request:
    paths:
      - 'UserMicroservice/**'

jobs:
  check-user-schema:
    name: Check User Microservice Schema diff
    uses: ./.github/workflows/check-schema.yaml
    with:
      service-name: UserMicroservice