name: User Microservice CI

on:
  pull_request:
    paths:
      - 'UserMicroservice/**'
      - 'UserMicroservice.Tests/**'
  workflow_call:
    secrets:
      PACT_BROKER:
        required: true
      PACT_BROKER_USERNAME:
        required: true
      PACT_BROKER_PASSWORD:
        required: true

jobs:
  check-user-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check User Microservice Schema diff
        uses: ./.github/actions/check-schema
        with:
          service-name: UserMicroservice
  
  verify-contract:
    runs-on: ubuntu-latest
    needs: check-user-schema
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Verify consumer contract against provider
        run: |
          echo "Verifying pact..."
          cd UserMicroservice.Tests
          dotnet restore
          
          PACT_PUBLISH_VERIFICATION_RESULTS=true \
          GIT_SHA=${{ github.sha }} \
          GIT_BRANCH=${{ github.ref_name }} \
          PactBroker__PactBrokerUri=${{ secrets.PACT_BROKER }} \
          PactBroker__PactBrokerUsername=${{ secrets.PACT_BROKER_USERNAME }} \
          PactBroker__PactBrokerPassword=${{ secrets.PACT_BROKER_PASSWORD }} \
          dotnet test