name: User Microservice CI

on:
  pull_request:
    paths:
      - 'UserMicroservice/**'
      - 'UserMicroservice.Tests/**'
  workflow_call:

jobs:
  check-user-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check User Microservice Schema diff    
        uses: ./.github/actions/check-schema
        with:
          service-name: UserMicroservice
  
  verify-contract:
    runs-on: ubuntu-latest
    env:
      PROVIDER_NAME: UserMicroservice
      CONSUMER_NAME: GroupMicroservice
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Verify consumer contract against provider
        run: |
          echo "Verifying pact..."
          cd UserMicroservice.Tests
          dotnet restore
          PactBroker__PactBrokerUri=${{ secrets.PACT_BROKER }} PactBroker__PactBrokerUsername=${{ secrets.PACT_BROKER_USERNAME }} PactBroker__PactBrokerPassword=${{ secrets.PACT_BROKER_PASSWORD }} dotnet test