name: User Microservice CI

on:
  pull_request:
    paths:
      - 'UserMicroservice/**'
      - 'UserMicroservice.Tests/**'
  workflow_call:

jobs:
  check-user-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Check User Microservice Schema diff    
        uses: ./.github/actions/check-schema.yaml
        with:
          service-name: UserMicroservice