name: Main Workflow

on:
  pull_request: 
    branches:
      - main
  push: 
    branches:
      - main

jobs:
  user-ms-workflow:
    name: Full User Microservice Workflow
    uses: ji-easv/EvolvingDistributedSystems/.github/workflows/user-ms-workflow.yaml@main
    secrets: inherit

  group-ms-workflow:
    name: Full Group Microservice Workflow
    uses: ji-easv/EvolvingDistributedSystems/.github/workflows/group-ms-workflow.yaml
    secrets: inherit